"""Align schema with corrected models

Revision ID: 1a3e000a2aea
Revises: e8f3ee93da97
Create Date: 2025-12-28 14:34:10.063734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3e000a2aea'
down_revision: Union[str, Sequence[str], None] = 'e8f3ee93da97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # config_themes org_id must not be null
    op.alter_column('config_themes', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # documents: add org_id as nullable first
    op.add_column('documents', sa.Column('org_id', sa.Integer(), nullable=True))
    op.alter_column('documents', 'kb_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('documents_org_id_fkey', 'documents', 'organizations', ['org_id'], ['id'])

    # guest_identities: switch from tenant_id to org_id
    op.add_column('guest_identities', sa.Column('org_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('guest_identities_tenant_id_fkey'), 'guest_identities', type_='foreignkey')
    op.create_foreign_key('guest_identities_org_id_fkey', 'guest_identities', 'organizations', ['org_id'], ['id'])
    op.drop_column('guest_identities', 'tenant_id')

    # knowledge_bases: add tenant_id
    op.add_column('knowledge_bases', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('knowledge_bases', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('knowledge_bases_tenant_id_fkey', 'knowledge_bases', 'tenants', ['tenant_id'], ['id'])

    # organizations must have tenant_id
    op.alter_column('organizations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # secrets: add tenant_id
    op.add_column('secrets', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('secrets', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('secrets_tenant_id_fkey', 'secrets', 'tenants', ['tenant_id'], ['id'])

    # tenants domain must not be null
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # users must have org_id
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # widgets: add tenant_id
    op.add_column('widgets', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('widgets', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('widgets_tenant_id_fkey', 'widgets', 'tenants', ['tenant_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widgets', type_='foreignkey')
    op.alter_column('widgets', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('widgets', 'tenant_id')
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'secrets', type_='foreignkey')
    op.alter_column('secrets', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('secrets', 'tenant_id')
    op.alter_column('organizations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.alter_column('knowledge_bases', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('knowledge_bases', 'tenant_id')
    op.add_column('guest_identities', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guest_identities', type_='foreignkey')
    op.create_foreign_key(op.f('guest_identities_tenant_id_fkey'), 'guest_identities', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('guest_identities', 'org_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'kb_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'org_id')
    op.alter_column('config_themes', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
