"""Align schema with models

Revision ID: e8f3ee93da97
Revises: 0f861d175027
Create Date: 2025-12-28 12:10:56.448356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8f3ee93da97'
down_revision: Union[str, Sequence[str], None] = '0f861d175027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_themes', sa.Column('theme_name', sa.String(length=255), nullable=True))
    op.add_column('config_themes', sa.Column('primary_color', sa.String(length=50), nullable=True))
    op.add_column('config_themes', sa.Column('secondary_color', sa.String(length=50), nullable=True))
    op.add_column('config_themes', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('config_themes', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('config_themes', 'logo_url')
    op.drop_column('config_themes', 'theme_json')
    op.drop_column('config_themes', 'display_name')
    op.drop_column('config_themes', 'welcome_message')
    op.drop_column('config_themes', 'published')
    op.add_column('documents', sa.Column('kb_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('documents_org_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_column('documents', 'org_id')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'type')
    op.drop_column('documents', 'published')
    op.drop_column('documents', 'url')
    op.add_column('guest_identities', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('guest_identities', sa.Column('session_token', sa.String(length=255), nullable=True))
    op.add_column('guest_identities', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'guest_identities', ['session_token'])
    op.drop_constraint(op.f('guest_identities_org_id_fkey'), 'guest_identities', type_='foreignkey')
    op.create_foreign_key(None, 'guest_identities', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('guest_identities', 'org_id')
    op.drop_column('guest_identities', 'origin')
    op.drop_column('guest_identities', 'expires_at')
    op.add_column('knowledge_bases', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('knowledge_bases_org_id_fkey'), 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_bases', 'organizations', ['org_id'], ['id'])
    op.drop_column('knowledge_bases', 'source_type')
    op.drop_column('knowledge_bases', 'kb_url')
    op.drop_column('knowledge_bases', 'kb_name')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('secrets_org_id_fkey'), 'secrets', type_='foreignkey')
    op.create_foreign_key(None, 'secrets', 'organizations', ['org_id'], ['id'])
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'workos_user_id')
    op.drop_column('users', 'role')
    op.drop_constraint(op.f('widgets_org_id_fkey'), 'widgets', type_='foreignkey')
    op.create_foreign_key(None, 'widgets', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widgets', type_='foreignkey')
    op.create_foreign_key(op.f('widgets_org_id_fkey'), 'widgets', 'tenants', ['org_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('workos_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'secrets', type_='foreignkey')
    op.create_foreign_key(op.f('secrets_org_id_fkey'), 'secrets', 'tenants', ['org_id'], ['id'])
    op.alter_column('organizations', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('knowledge_bases', sa.Column('kb_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('knowledge_bases', sa.Column('kb_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('knowledge_bases', sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_bases_org_id_fkey'), 'knowledge_bases', 'tenants', ['org_id'], ['id'])
    op.drop_column('knowledge_bases', 'name')
    op.add_column('guest_identities', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('guest_identities', sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('guest_identities', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'guest_identities', type_='foreignkey')
    op.create_foreign_key(op.f('guest_identities_org_id_fkey'), 'guest_identities', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'guest_identities', type_='unique')
    op.drop_column('guest_identities', 'created_at')
    op.drop_column('guest_identities', 'session_token')
    op.drop_column('guest_identities', 'tenant_id')
    op.add_column('documents', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_org_id_fkey'), 'documents', 'organizations', ['org_id'], ['id'])
    op.alter_column('documents', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'kb_id')
    op.add_column('config_themes', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('config_themes', sa.Column('welcome_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('config_themes', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('config_themes', sa.Column('theme_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('config_themes', sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('config_themes', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('config_themes', 'created_at')
    op.drop_column('config_themes', 'secondary_color')
    op.drop_column('config_themes', 'primary_color')
    op.drop_column('config_themes', 'theme_name')
    # ### end Alembic commands ###
