import os

DB_PASSWORD = os.getenv("DB_PASSWORD")
POSTGRES_URL = os.getenv("POSTGRES_URL")
WORKOS_API_KEY = os.getenv("WORKOS_API_KEY")
WORKOS_CLIENT_ID = os.getenv("WORKOS_CLIENT_ID")
WORKOS_REDIRECT_URI = os.getenv("WORKOS_REDIRECT_URI")
JWT_ACCESS_SECRET = os.getenv("JWT_ACCESS_SECRET")
JWT_REFRESH_SECRET = os.getenv("JWT_REFRESH_SECRET")
JWT_GUEST_SECRET = os.getenv("JWT_GUEST_SECRET")
APP_BASE_URL = os.getenv("APP_BASE_URL")
CHAT_BASE_URL = os.getenv("CHAT_BASE_URL")
SESSION_COOKIE_DOMAIN = os.getenv("SESSION_COOKIE_DOMAIN")
APPINSIGHTS_CONNECTION_STRING = os.getenv("APPINSIGHTS_CONNECTION_STRING")
